# Generated by Django 4.1.1 on 2022-09-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='image',
        ),
    ]
